services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MyKitchen
      POSTGRES_USER: HungryClient
      POSTGRES_PASSWORD: ChowingF00d!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: